### PR TITLE
feat(build): update ng-packagr to the latest version and adapt the 'build' script to use the NG CLI 'ng build' command instead

### PR DESCRIPTION
**Pull request by christophercr**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/ngx-form-errors/blob/master/CONTRIBUTING.md#-commit-message-guidelines
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The build process is using `ng-packagr` as a standalone library and it is using and old version.

## What is the new behavior?
The `ng-packagr` library is now upgraded to the latest version which brings these benefits:
- we can now use the NG CLI `ng build` command that integrates the `ng-packagr` library instead of using it as a standalone library
- the build is done using all the recommended options from `ng-packagr` thanks to its integration with the NG CLI.

Moreover, we can now use the `lint` and `test` commands from the NG CLI too if needed (by running `npm run ng -- lint` and `npm run ng -- test`) 👍 

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by SuperITMan** [comment]
While we are doing changes for ng-packagr, what would you think of changing the content of the "tsconfig.json" file and adding a "tsconfig.lib.json" file as we have for the Stark packages ? 😊

**Comment by christophercr** [comment]
@SuperITMan you're right... I'll add the `tsconfig.lib.json` file 👍

**Comment by SuperITMan** [comment]
@christophercr I see that my message was unclear after reading it again 😜
For the "tsconfig.json" file I think we should use nbb/code-style as we do in Stark 😊
What do you think?

**Comment by christophercr** [comment]
I updated this PR as suggested by @SuperITMan: I've added another commit to integrate the tsconfig from NBB `code-style`... so there was some TypeScript code that needed to be adapted.

I didn't enabled the `strictPropertyInitialization` rule for now, I'll take core of that in another PR ;)

**Pull request merged**
